# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MN', 'Manga'), ('EM', 'Email'), ('UR', 'Url')], default='UR', max_length=2)),
            ],
        ),
    ]
