# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplefeed', '0002_auto_20161113_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='diff',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
