# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplefeed', '0003_target_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='epoch',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
